language: node_js
node_js:
    - '10'
cache: yarn
script:
    - yarn build
deploy:
    on:
        branch: develop
    provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: $AWS_S3_BUCKET
    local_dir: build
    skip_cleanup: true
    acl: public_read
notifications:
    email:
        - graham.rogers@servicemaster.com
